SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1024
FPS = 60

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 100

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3
PLAYER_SPEED_BOOST = 2.0

SHOT_RADIUS = 5
SHOT_SPEED = 500

CONTROLLER_DEAD_ZONE = 0.2

INVULENERABILITY_TIME = .25
INVULENERABILITY_COOLDOWN = 2.0

MINOR_BUFF_RADIUS = 10
MINOR_BUFF_RADIUS_INCREASE = 5